export const providerData = {
  name: "Happy Kids",
  rating: 4.8,
  totalReviews: 127,
  location: "123 Main St, San Francisco, CA 94105",
  images: [
    "/provider1.jpg",
    "/provider2.jpg",
    "/provider3.jpg",
    "/provider4.jpg",
    "/provider5.jpg",
  ],
  services: [
    {
      id: 1,
      name: "Full Day Program",
      description: "Monday to Friday, 8:00 AM - 5:00 PM",
      price: "$75",
      duration: "per day",
      availability: "Limited spots",
    },
    {
      id: 2,
      name: "Half Day Program",
      description: "Monday to Friday, 8:00 AM - 12:00 PM",
      price: "$45",
      duration: "per day",
      availability: "Available",
    },
    {
      id: 3,
      name: "After School Care",
      description: "Monday to Friday, 3:00 PM - 6:00 PM",
      price: "$35",
      duration: "per day",
      availability: "Available",
    },
  ],
  reviews: [
    {
      id: 1,
      author: "Sarah M.",
      rating: 5,
      date: "2 months ago",
      comment: "Absolutely amazing experience! The staff is incredibly caring and professional. My child loves going here every day.",
      avatar: "/avatar1.jpg",
    },
    {
      id: 2,
      author: "John D.",
      rating: 5,
      date: "3 months ago",
      comment: "Best childcare center in the area. The facilities are clean and well-maintained. Highly recommended!",
      avatar: "/avatar2.jpg",
    },
    {
      id: 3,
      author: "Emily R.",
      rating: 4,
      date: "1 month ago",
      comment: "Great environment for kids to learn and grow. The curriculum is well-structured and engaging.",
      avatar: "/avatar3.jpg",
    },
  ],
  ratingDistribution: {
    5: 85,
    4: 25,
    3: 10,
    2: 5,
    1: 2,
  },
  features: [
    "Licensed Provider",
    "Background Checked",
    "First Aid Certified",
    "CPR Certified",
  ],
  businessHours: [
    { day: "Monday", hours: "7:00 AM - 6:00 PM" },
    { day: "Tuesday", hours: "7:00 AM - 6:00 PM" },
    { day: "Wednesday", hours: "7:00 AM - 6:00 PM" },
    { day: "Thursday", hours: "7:00 AM - 6:00 PM" },
    { day: "Friday", hours: "7:00 AM - 6:00 PM" },
    { day: "Saturday", hours: "Closed" },
    { day: "Sunday", hours: "Closed" },
  ],
  coordinates: {
    lat: 37.7749,
    lng: -122.4194,
  },
}; 